---
AWSTemplateFormatVersion: "2010-09-09"

Description: "test"


Parameters:
  RoleName:
    Type: String
  DummName:
    Type: String

Resources:
  TestIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - '*'
                Resource: '*'
  IAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Ref DummName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - '*'
                Resource: '*'
  # MyLambda:
  #   Type: 'AWS::Serverless::Function'
  #   Properties:
  #     FunctionName: test-function
  #     Handler: test_function.lambda_handler
  #     Runtime: python3.6
  #     CodeUri:
  #       Bucket: !Ref BucketName
  #       Key: node-app/lambda.zip
  #     Description: test.
  #     Role: !GetAtt TestIAMRole.Arn
  #     Timeout: 900
  # MyLambda:
  #   Type: 'AWS::Serverless::Function'
  #   Properties:
  #     FunctionName: test-function
  #     Handler: test_function.lambda_handler
  #     Runtime: python3.6
  #     CodeUri:
  #       Bucket: !Ref BucketName
  #       Key: node-app/lambda.zip
  #     Description: test.
  #     Role: !GetAtt TestIAMRole.Arn
  #     Timeout: 900
  # MyLambda:
  #   Type: 'AWS::Serverless::Function'
  #   Properties:
  #     FunctionName: test-function
  #     Handler: test_function.lambda_handler
  #     Runtime: python3.6
  #     CodeUri:
  #       Bucket: !Ref BucketName
  #       Key: node-app/lambda.zip
  #     Description: test.
  #     Role: !GetAtt TestIAMRole.Arn
  #     Timeout: 900
